services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynet

  parser:
    build:
      context: .
      dockerfile: parser/Dockerfile
    container_name: parser
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: python parser/main.py
    networks:
      - mynet

  stats:
    build:
      context: .
      dockerfile: stats/Dockerfile
    container_name: stats
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - mynet

volumes:
  pgdata:

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.250.0/24